name: Deploy CDK Project

on:
  push:
    paths:
      - 'cdk-example/**'
  pull_request:
    paths:
      - 'cdk-example/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Node.js dependencies
        working-directory: ./cdk-example
        run: npm ci
      
      - name: Build CDK TypeScript project
        working-directory: ./cdk-example
        run: npm run build
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Cache Gradle files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Build and Zip Java Lambda
        working-directory: ./cdk-example/lib/java-example/lambda/
        run: ./gradlew buildZip

      - name: Deploy CDK stack
        working-directory: ./cdk-example
        run: npx cdk deploy --all --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-1'
